# registry
[registry]
url = "127.0.0.1:8090"
app-install-path = "installs"

[invokers.grpc]
bind_address = "0.0.0.0:9999"

[app_store]
base_idr = "appfiles"
[app_store.warg_config]
defaultUrl = "http://127.0.0.1:8090/"
registriesDir = "registries"
contentDir = "content"
[app_store.auth]


