/// An interface for a consumer relying on push-based message delivery.
interface handler {
    use messaging-types.{event, error}

    /// Creates an on-receive handler push-based message delivery.
    on-receive: func(e: event) -> result<_, error>
}