[package]
name = "micro-async-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
tokio = { workspace = true, features = ["rt-multi-thread", "time", "macros"] }